language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libdmtx0a
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install --no-dev --no-interaction --no-ansi
install:
  - poetry install
script: pytest